project:
  name: "default"

application1:
  name: "titan"
  destination:
    namespace: "acme"
    server: "https://0.0.0.0:42497"
  source:
    path: "webserver"
    repourl: "https://github.com/ctablero/majarete.git"
    targetrevision: "HEAD"
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
