project:
  name: "default"

application1:
  name: "my-application1"
  destination:
    namespace: "default"
    server: "https://kubernetes.default.svc"
  source:
    path: "webserver"
    repourl: "https://github.com/ctablero/majarete.git"
    targetrevision: "HEAD"
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true

application2:
  name: "my-application2"
  destination:
    namespace: "default"
    server: "https://kubernetes.default.svc"
  source:
    path: "pvs"
    repourl: "https://github.com/ctablero/majarete.git"
    targetrevision: "HEAD"
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
